export const LOGINSCREEN = 'LOGINSCREEN';
export const HOMESCREEN = 'HOMESCREEN';

export const TABNAVIGATOR = 'TABNAVIGATOR';
export const HISTORY_MONEY = 'HISTORY_MONEY';
export const HISTORY_LOGIN = 'HISTORY_LOGIN';
export const LISTCUSTOMER = 'LISTCUSTOMER';
export const REQUIREMONEY = 'REQUIREMONEY';
export const DETAIL_REQUIRE_MONEY = 'DETAIL_REQUIRE_MONEY';
export const DETAIL_HISTORY_MONEY = 'DETAIL_HISTORY_MONEY';
export const DETAIL_CUSTOMER = 'DETAIL_CUSTOMER';
export const DETAIL_WITHDRAW = 'DETAIL_WITHDRAW';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const WITHDRAW = 'WITHDRAW';
